# Generated by Django 2.1.7 on 2019-04-16 04:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('x_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to='')),
                ('y_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to='')),
                ('best', models.CharField(blank=True, max_length=200)),
                ('image', models.TextField(blank=True)),
                ('trials', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to='')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
