# Generated by Django 2.2.2 on 2019-06-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=30)),
                ('raw', models.FileField(blank=True, upload_to='raw/')),
                ('mod', models.FileField(blank=True, upload_to='model/')),
                ('upload', models.FileField(blank=True, upload_to='upload/')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('F', 'Finished'), ('W', 'Waiting'), ('E', 'Error'), ('P', 'Process'), ('C', 'Calculating')], default='P', max_length=10)),
            ],
        ),
    ]
