# Generated by Django 2.1.7 on 2019-04-16 11:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('W', 'Waiting'), ('E', 'Error'), ('C', 'Calculating')], default='W', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='trials',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='x_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='y_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/'), upload_to=''),
        ),
    ]
