# Generated by Django 2.2.2 on 2019-07-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('W', 'Waiting'), ('E', 'Error'), ('I', 'Idle'), ('P', 'Process'), ('C', 'Calculating')], default='I', max_length=10),
        ),
    ]
