# Generated by Django 2.2.2 on 2019-06-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='data',
            new_name='raw',
        ),
        migrations.AlterField(
            model_name='job',
            name='mod',
            field=models.FileField(blank=True, upload_to='model/'),
        ),
    ]
