# Generated by Django 2.2.1 on 2019-06-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190602_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='csv_data',
            new_name='data',
        ),
    ]
