# Generated by Django 2.2 on 2019-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190416_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='best',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trials',
        ),
        migrations.AddField(
            model_name='job',
            name='mod',
            field=models.FileField(blank=True, upload_to='result/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='x_file',
            field=models.FileField(blank=True, upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='y_file',
            field=models.FileField(blank=True, upload_to='raw/'),
        ),
    ]
