# Generated by Django 2.1.7 on 2019-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
