# Generated by Django 2.1.7 on 2019-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('x_file', models.FileField(upload_to='')),
                ('y_file', models.FileField(upload_to='')),
                ('create_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('C', 'Complete'), ('P', 'Processing'), ('W', 'Waiting'), ('E', 'Error')], max_length=20)),
            ],
        ),
    ]
