# Generated by Django 2.1.7 on 2019-04-09 05:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='result',
            field=models.FileField(default=False, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/result'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='x_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/cal_file'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='y_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/cal_file'), upload_to=''),
        ),
    ]
