# Generated by Django 2.1.7 on 2019-04-10 11:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190409_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.FileField(default=False, storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/result/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='x_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/cal_file/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='y_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/ai4chem/media/cal_file/'), upload_to=''),
        ),
    ]
